#!/usr/bin/env bash

clear
set -euo pipefail

source "./lib/log.sh"
source "./lib/helpers.sh"
source "./lib/prompt.sh"

source "./menu.sh"
source "./mirror.sh"
source "./format_partition.sh"
source "./package.sh"
source "./locale.sh"
source "./network.sh"
source "./adduser.sh"
source "./pacman.sh"
source "./swap.sh"
source "./storage.sh"
source "./bootloader.sh"
source "./hibernation.sh"

CPU_VENDOR=$(lscpu | grep "^Vendor ID" | awk '{print $3}')

export CPU_VENDOR
export ROOT_MOUNTPOINT="/mnt"
export ESP_MOUNTPOINT="$ROOT_MOUNTPOINT/boot"

timezone
efi_partition
root_partition
storage
swap
username
root_password
user_password
kernel
if [[ "${SWAP_METHOD}" -eq "1" ]]; then
    bootloader
fi
summary

if ! [[ "${CONFIRM_INSTALL}" =~ [Yy] ]]; then
    clear
    print_color "${GREEN}" "Good bye.\n"
    exit 1
fi

clear
setting_mirror
format_partition
install_package
setting_locale
setting_network
adduser
setting_pacman
setting_swap
setting_storage
install_bootloader
# setting_hibernation

arch-chroot "${ROOT_MOUNTPOINT}" mkinitcpio -P

echo "# <file system> <dir> <type> <options> <dump> <pass>" | tee "${ROOT_MOUNTPOINT}"/etc/fstab &>/dev/null
genfstab -t UUID "${ROOT_MOUNTPOINT}" >>"${ROOT_MOUNTPOINT}"/etc/fstab

clear
success "Installing arch"
